# Generated by Django 4.0.6 on 2024-07-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='capacity',
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.theater'),
        ),
        migrations.AddField(
            model_name='seat',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'seat_number', 'row')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='section',
        ),
    ]
