# Generated by Django 4.0.6 on 2024-07-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_theater_capacity_seat_theater_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'seat_number')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='y_coordinate',
        ),
    ]
